services:
  - type: web
    name: yuva-sansad
    env: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p 10000 yuva_sansad.asgi:application
    preDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput